-- Insert into BANKING_SYSTEM_USER
INSERT INTO FIT5042.BANKING_SYSTEM_USER (LAST_NAME, FIRST_NAME, EMAIL, PASSWORD, "TYPE", ADDRESS, phone_number)
	VALUES ('Leung', 'Eddie' , 'eddieleung@student.monash.edu', '1111', 'Public', '24 Boston Avenue Malvern East Victoria 3145','0411234567');
INSERT INTO FIT5042.BANKING_SYSTEM_USER (LAST_NAME, FIRST_NAME, EMAIL, PASSWORD, "TYPE", ADDRESS, phone_number)
	VALUES ('Huang', 'Jennifer' , 'huangjennifer@student.monash.edu', '2222', 'Public', '11 Bettina Street Clayton Victoria 3168','0422334335');
INSERT INTO FIT5042.BANKING_SYSTEM_USER (LAST_NAME, FIRST_NAME, EMAIL, PASSWORD, "TYPE", ADDRESS, phone_number)
	VALUES ('Steller', 'Luke' , 'stellerluke@monashbank.com.au', '3333', 'Bank Worker', '3 Wattle Avenue Glen Huntly Victoria 3163','0409233432');

-- Insert into BANKING_TRANSACTION
INSERT INTO FIT5042.BANKING_TRANSACTION (BANKING_TRANSACTION_NAME, "TYPE", DESCRIPTION, USER_IDNUMBER, AMOUNT) 
	VALUES ('travel', 'Debit', 'travel to the Sydney', 1, 500);
INSERT INTO FIT5042.BANKING_TRANSACTION (BANKING_TRANSACTION_NAME, "TYPE", DESCRIPTION, USER_IDNUMBER, AMOUNT) 
	VALUES ('salary', 'Credit', 'Aug 2017', 1, 3000);
INSERT INTO FIT5042.BANKING_TRANSACTION (BANKING_TRANSACTION_NAME, "TYPE", DESCRIPTION, USER_IDNUMBER, AMOUNT) 
	VALUES ('dinner', 'Debit', 'in CBD', 2, 10);
INSERT INTO FIT5042.BANKING_TRANSACTION (BANKING_TRANSACTION_NAME, "TYPE", DESCRIPTION, USER_IDNUMBER, AMOUNT) 
	VALUES ('salary', 'Credit', 'Sep 2017', 2, 4000);

-- Insert into BANKING_ACCOUNT
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('classic', 1000, 1);
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('saver', 2000, 1);
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('reward', 3000, 1);
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('classic', 1000, 2);
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('saver', 2000, 2);
INSERT INTO FIT5042.BANKING_ACCOUNT (ACCOUNT_TYPE, BALANCE, USER_IDNUMBER) 
	VALUES ('reward', 3000, 2);